{
    "name": "Agentic AI Integration with Livechat",
    "version": "16.0.1.0.0",
    "summary": "Abstract agentic, multi-provider, RAG-enabled AI assistant for Odoo Livechat and Discuss with function calling.",
    "description": "Abstract, extensible, agent-based AI livechat integration for Odoo 16 CE. Multi-provider, tool-based, function calling orchestration, minimal lock-in.",
    "author": "Vilmos Balazs",
    "website": "https://klebromshop.ro",
    "category": "Tools",
    "depends": ["base", "website_livechat", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/default_providers.xml",
        "views/livechat_templates.xml",
        "views/agent_provider_views.xml",
        "views/agent_test_wizard.xml",
        "views/agent_tool_registry_views.xml",
        "views/agent_tool_metadata_views.xml",
        "views/agent_tool_sync_wizard_views.xml",
        "views/agent_tool_loader_wizard_views.xml",
        "views/agent_prompt_template_views.xml",
        "views/agent_prompt_registry_views.xml",
        "views/agent_prompt_confirm_wizard_views.xml",
        "views/agent_prompt_loader_wizard_views.xml",
        "views/agent_tool_metadata_actions.xml",
        "views/meilisearch_config_views.xml",
        "views/meilisearch_browse_views.xml",
        "views/agent_test_menu.xml",
        "data/prompt_template_sync.xml"
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
